### ISSUE TITLE
UI Improvement Needed

### ISSUE THREAD

**Issue by tauseefansari** [tauseefansari/Digital-Billing-System#4]
help me providing a better design for UI and Animations

**Comment by saif71** [comment]
Hi, Whats sort of UI improvements you need? I think I can help .

**Comment by tauseefansari** [comment]
I just want a nice looking User Interface because I don't  have any idea regarding UI / UX Design

**Comment by tauseefansari** [comment]
> Hi, Whats sort of UI improvements you need? I think I can help . 

If you want to contribute send me a pull request as per your own design

Take your time 🙂

**Comment by saif71** [comment]
I'm a UX designer, not an android developer. Hence I can't update the UI on the code level. I can provide the design. Somebody needs to implement the code.

**Comment by tauseefansari** [comment]
> I'm a UX designer, not an android developer. Hence I can't update the UI on the code level. I can provide the design. Somebody needs to implement the code. 

Okay, Then i will try to update it in the code and merge it

**Comment by tauseefansari** [comment]
> I'm a UX designer, not an android developer. Hence I can't update the UI on the code level. I can provide the design. Somebody needs to implement the code. 

Does it requires any charge?

**Comment by saif71** [comment]
> 
> 
> > I'm a UX designer, not an android developer. Hence I can't update the UI on the code level. I can provide the design. Somebody needs to implement the code.
> 
> Does it requires any charge?

I will try to keep existing functionality intact. Just change the interface level. I will create a separate issue for each design update.

**Comment by tauseefansari** [comment]
> > I'm a UX designer, not an android developer. Hence I can't update the UI on the code level. I can provide the design. Somebody needs to implement the code. 
> 
> Does it requires any charge?

I said do i have to pay something for this?

**Comment by saif71** [comment]
> 
> 
> > > I'm a UX designer, not an android developer. Hence I can't update the UI on the code level. I can provide the design. Somebody needs to implement the code.
> > 
> > 
> > Does it requires any charge?
> 
> I said do i have to pay something for this?

No charges needed. As long as : 
- You keep it open source.
- You don't use it for any kind of monetization. 
- You don't use it for any kind of illegal or malicious works. 
- You don't require urgent contributions/tasks. 
- Give me credit as a contributing member. 

I mean we should follow the ground rules of open source contribution, right? 😊😊

**Comment by tauseefansari** [comment]
> > 
> > 
> > > > I'm a UX designer, not an android developer. Hence I can't update the UI on the code level. I can provide the design. Somebody needs to implement the code.
> > > 
> > > 
> > > Does it requires any charge?
> > 
> > I said do i have to pay something for this?
> 
> No charges needed. As long as : 
> - You keep it open source.
> - You don't use it for any kind of monetization. 
> - You don't use it for any kind of illegal or malicious works. 
> - You don't require urgent contributions/tasks. 
> - Give me credit as a contributing member. 
> 
> I mean we should follow the ground rules of open source contribution, right? 😊😊

Okay, Thanks

Even i am also a student and i made this application for my own practice purposes not any commercial or professional purpose

Because we learn by doing 😊
